id: IBE44A07E
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-14 15:00:21.994062+00:00
last_modified: 2022-12-14 15:00:21.994072+00:00
source_metadata:
  creationtool: 84000-translation-memory
  creationtoolversion: 1.0.0.0
  datatype: PlainText
  segtype: phrase
  adminlang: en
  srclang: bo
  o-tmf: TEI
  creationdate: '2018-07-18T06:21:33.896Z'
  creationid: dirk
  eft-text-id: UT22084-059-014
  xmlns-eft: http://read.84000.co/ns/1.0
  title: Toh_171-The_Questions_of_an_Old_Lady-v1
bases:
  980B:
    source_metadata: null
    order: 1
    base_file: 980B.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
